In [3]:
#Comprehensions

keyfile = 'DataFiles/key.txt'

def dictionaryKeyFile(keyfile):
    key = {}
    with open(keyfile,'r') as f:
        for line in f:
            line = line.split()
            key[line[0]] = line[1]
    return key  

key = dictionaryKeyFile(keyfile)

evenkeys={item for item in key.items() if int(item[0]%2 == 0)}
evenkeys

TypeError: not all arguments converted during string formatting

In [4]:

key = dictionaryKeyFile(keyfile)
evenkeys={item for item in key}
evenkeys

{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}

### Numpy Library 

- Processing  N-Dimensional arrays


In [67]:
import numpy as np

li = [1,2,3,'z']
a = np.array(li)
a
b= np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
m3 = np.random.randint(0,2,size=(3,3))
m3
m3[0][1]

0

In [75]:
m3 = np.random.randint(0,2,size=(3,3,3))
m3[0][0][0]
m3

array([[[0, 0, 0],
        [1, 0, 0],
        [1, 1, 0]],

       [[1, 0, 0],
        [0, 1, 1],
        [0, 0, 1]],

       [[1, 1, 0],
        [1, 1, 1],
        [0, 1, 0]]])

In [93]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes

m3[:2, :1]

m3[:, 1]  #frist colum of m3

m3[1,:]   #frist row of the m3

array([[1, 0, 0],
       [0, 1, 1],
       [0, 0, 1]])

In [23]:
x= [1,2,3,4,5,6,7,8,9]
x[-5:]

[5, 6, 7, 8, 9]

In [29]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
# row vector

b[:,np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [32]:
d=b+1 #'1' is the considered as the constent value
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Pandas
#### Use Cases
- Data Cleaning
- Data Transformation
- Data Analysis

#### Notations
- Series
- Data Frames


In [39]:
import pandas as pd

internal1={'s1':21,'s2':18,'s3':24}

internal1=pd.Series(internal1)

internal2 = {'s1':11,'s2':23,'s3':12}
internal2 = pd.Series(internal2)
internal2

s1    11
s2    23
s3    12
dtype: int64

In [40]:
final = {'Internal1':internal1,'Internal2':internal2}
final = pd.DataFrame(final)
final

Internal1  Internal2
s1         21         11
s2         18         23
s3         24         12

In [41]:
final['Internal1']

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [42]:
final.columns # Names of All Columns 

Index(['Internal1', 'Internal2'], dtype='object')

In [43]:
final.values # Lists of All Rows

array([[21, 11],
       [18, 23],
       [24, 12]], dtype=int64)

In [45]:
final.values[2]

array([24, 12], dtype=int64)

In [48]:
final.values[2,0]
final.values[2][0]  # Both Notations are gives same result.

24

In [50]:
for row in final.values:
    print('Internal 1:',row[0],',Internal 2 :',row[1])
    

Internal 1: 21 ,Internal 2 : 11
Internal 1: 18 ,Internal 2 : 23
Internal 1: 24 ,Internal 2 : 12


In [86]:
final.loc['s4'] = [12,15]  # Location of the table

final

Internal1  Internal2
s1         21         11
s2         18         23
s3         12         25
s4         12         15

In [88]:
 final.drop('s4')

Internal1  Internal2
s1         21         11
s2         18         23
s3         12         25

In [92]:
#final = final.drop('s3')
final

Internal1  Internal2
s1         21         11
s2         18         23
s4         12         15

In [65]:
final.values[2]=[12,25]
final

Internal1  Internal2
s1         21         11
s2         18         23
s3         12         25
s4         12         15

In [ ]:
for row in incomedf.values:
    print(row[1],':',row[-1])

In [ ]:
# Average income of a particular state

sum = 0
for i in range(2,11):
    sum += incomedf.values[2][i]
sum//len(incomedf.values[2][2:])

In [ ]:
# Average income of all states in year 2012
sum = 0
for row in range(2,11):
    sum += row[-2]
sum//len(incomedf.values)
    
    
    